### ISSUE TITLE
Issue with other factorio mod

### ISSUE THREAD

**Issue by andremmvgabriel** [cameronleger/blueprint-sandboxes#3]
Hey!

I have encountered an error that is somewhat critical, but I believe it can only be achieved with the usage of another mod. This other mod is factorissimo2.

So, the problem is that I have managed to get stuck inside the blueprint sandbox. Once I entered in the sandbox mode, I have placed one of the warehouses from factorissimo2, went inside it and tried to exit the sandbox (which makes you return to the sandbox).

I think the problem with this is that once you go inside the warehouse, it no longer considers that you are in the sandbox world, and registers it as the world you will go back to once you exit the mode. After that, you will get stuck forever inside the sandbox.

**Comment by cameronleger** [comment]
This is a known (though not clearly documented) bug with the original Factorissimo2 mod. There is not much I can about it, outside of looking for ways to document that or trying to prevent it from happening (by preventing you from placing them, I guess).

This mod _does_ support the [NotNotMelon fork](https://mods.factorio.com/mod/factorissimo-2-notnotmelon), and it behaves as well as it can given the integration.

**Comment by andremmvgabriel** [comment]
Ah, thank you for letting me know that. And I am sorry that I have bothered you with an issue that isn't related with the project. Will close the issue now.

**Comment by cameronleger** [comment]
Don't worry about it :)
