### ISSUE TITLE
Request: Please allow ghosts to be placed via a toggle

### ISSUE THREAD

**Issue by Shovinus** [cameronleger/blueprint-sandboxes#6]
I am currently designing some blue prints, but there are somethings where I need to test how constructions robots and ghost scanner interact with actual ghosts (specifically tiles) but I can't test this in the sandbox because there is no way to actually place a ghost.

Can you and a toggle or maybe a tool to convert to ghost like how you have for ores?

Great mod though.

**Comment by cameronleger** [comment]
Totally, the newest version includes this as a setting.
